# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/Pavan kumar/Downloads/tmart-supabase-auth/android/.jdk21/jdk-21.0.5+11
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
android.useAndroidX=true
