-- Safe Supabase Migration to ensure all required and AI-prep columns exist in public.products table

ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT uuid_generate_v4();
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT 'Product';
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS barcode VARCHAR(100);
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'General';
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS brand TEXT NULL;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS subcategory TEXT NULL;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS pack_size TEXT NULL;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS unit VARCHAR(50) DEFAULT 'pcs';
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS selling_price NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS mrp NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS stock_quantity INT DEFAULT 0;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS minimum_stock INT DEFAULT 10;
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE IF EXISTS public.products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
